### ISSUE TITLE
Navbar scrollbar

### ISSUE THREAD

**Issue by rpanai** [shoval/jupyter-navbar#1]
Hi, thank you for your work. I was wondering if it's possible to add a separate scrollbar for the ToC? I know that one has to use `overflow-y: scroll` somewhere inside the css but I couldn't find where.

**Comment by shoval** [comment]
I tried that, and it turned out to be a bit more tricky than expected. I will keep this issue open until I manage to make it work. Thanks for submitting.

**Comment by shoval** [comment]
@rpanai, I just ran a demo of a notebook with many headers, and the vertical scrollbar seems to work fine (see screenshot), and appears whenever there is not enough space for all items. Have you tried it? Does it not behave this way for you?

![image](https://user-images.githubusercontent.com/1183305/37023986-4fb83924-2130-11e8-9836-9260ac01f635.png)

The only problem I haven't managed to solve yet is the "collapse" button scrolling with the text instead of staying in place.

**Comment by rpanai** [comment]
@shoval Have you modified  the `overflow-y` to have the side scroll? If yes in which section?

**Comment by shoval** [comment]
@rpanai no, I haven't changed anything. In my previous reply I simply forgot that I've already solved this issue. the `#nav_wrapper` element has a property `overflow-y: auto;` which allows for the scrolling. This wasn't enough to solve it originally, since there is a need for a constant height of the element for this to work. I ended up patching it with some JavaScript code on page resizes.

Does the scrolling work for you? Please add multiple headers to the notebook and let me know what you get. If the scrollbar doesn't appear, please share a screenshot.
