### ISSUE TITLE
Sub section numbering?

### ISSUE THREAD

**Issue by TRM13** [shoval/jupyter-navbar#7]
More of a feature request than a bug. Love this addition to Jupyter. Thanks. 

When I do up the mail heading with # and the sub-headings with ## I was hoping to get output like this:
1. Intro
   1.1 Stuff
   1.2 More stuff
2. Next Section
   2.1 Section 2 Stuff

instead I am getting this:
"1. First Section"
" ____ 2. Stuff"
" ____ 3. More stuff"
"4. Second Section"
" ____ 1. Section Stuff"

I've looked and found nothing. If there is a way to do it that would be great. 
Thanks again

**Comment by shoval** [comment]
The HTML ordered list behaves this way by default, so that's the reason for the current functionality. I've been meaning to implement what you've suggested for quite some time, but it seemed too complicated. Now that I searched around a bit, there seems to be a good pure CSS solution:
https://stackoverflow.com/a/26245056/4983290
So it seems quite straightforward. I'll try to get around to implement it this coming week. Thanks for your feedback.

**Comment by TRM13** [comment]
Thanks. I'm new to Jupyter and your navbar filled a hole nicely. Do you have a donation button?

**Comment by shoval** [comment]
@TRM13 - done! Let me know if you encounter any bugs as I did not have time to thoroughly test it. It was a bit tricky eventually, especially handling cases where levels are skipped (e.g. H4 directly under H2).

BTW - thanks for the donation offer, I will consider adding a button in the future.

**Comment by TRM13** [comment]
Works great. Thank you very much.
